Remove word "Version" from Vyxal release messages
Vyxal/VyxalBot2 pull request #62
Opened 2023-05-07 12:36 UTC by Lyxal

Because it doesn't look very nice in chat, but removing the word "version" from the release on github would break the tradition of 117 releases.

2023-05-07 14:29 UTC, nayakrujul approved these changes

2023-05-07 14:53 UTC, GingerIndustries commented
I don't like this, it involves too much special casing. I think it looks fine in chat.

2023-05-07 22:17 UTC, Lyxal commented
I on the other hand don't like it in chat. Besides, there's already special casing for the pins, and it's something I want for the bot.

2023-05-08 00:19 UTC, GingerIndustries commented
I don't like said special casing, and I don't want more of it

2023-05-08 00:20 UTC, GingerIndustries commented
The pin thing isn't really fixable without it, but this is by just changing how we name releases

2023-05-08 06:15 UTC, nayakrujul requested changes
https://chat.stackexchange.com/transcript/message/63528312#63528312

2023-05-08 12:25 UTC, GingerIndustries requested changes
Regex should also match `+`

2023-05-08 12:30 UTC, merged